using System.Text.Json;
using System.Text.Json.Serialization;

namespace LlmPocApp.Services;

public class EvaluationResult
{
    [JsonPropertyName("score")]
    public int Score { get; set; }

    [JsonPropertyName("reasoning")]
    public string Reasoning { get; set; } = string.Empty;
}

public class EvaluationService
{
    private readonly LlmChatService _chatService;

    public EvaluationService(LlmChatService chatService)
    {
        _chatService = chatService;
    }

    public async Task<EvaluationResult> EvaluateAsync(string goal, string expectedInput, string expectedOutput, string actualOutput)
    {
        var systemPrompt = @"You are an strict AI Judge.
Your job is to evaluate the quality of a Chatbot's response based on the defined Goal and Ground Truth (Expected Output).

Input Data:
1. Goal/Context: The persona and objective of the bot.
2. User Input: What the user said.
3. Expected Output: The ideal response (Ground Truth).
4. Actual Output: The response actually generated by the bot.

Criteria:
- Accuracy: Does it follow the instructions in the Goal?
- Tone: Does it match the persona?
- Similarity: Is the semantic meaning close to the Expected Output? (Exact match is not required, focusing on intent).

Output Format:
You MUST output a valid JSON object with the following structure:
{
    ""score"": (integer 0-100),
    ""reasoning"": ""(string, concise explanation of the score, in Traditional Chinese)""
}
Do not output markdown code blocks (```json). Just the raw JSON string.
";

        var userPrompt = $@"
[Goal/Context]:
{goal}

[User Input]:
{expectedInput}

[Expected Output]:
{expectedOutput}

[Actual Output]:
{actualOutput}
";

        try
        {
            var jsonResponse = await _chatService.GetRawResponseAsync(systemPrompt, userPrompt, "gpt-5.2-chat");
            
            // Clean up JSON markdown code blocks if present
            jsonResponse = jsonResponse.Replace("```json", "").Replace("```", "").Trim();
            if (jsonResponse.StartsWith("```json"))
            {
                jsonResponse = jsonResponse.Substring(7);
                if (jsonResponse.EndsWith("```"))
                {
                    jsonResponse = jsonResponse.Substring(0, jsonResponse.Length - 3);
                }
            }
            else if (jsonResponse.StartsWith("```")) 
            {
                jsonResponse = jsonResponse.Substring(3);
                if (jsonResponse.EndsWith("```"))
                {
                    jsonResponse = jsonResponse.Substring(0, jsonResponse.Length - 3);
                }
            }

            var result = JsonSerializer.Deserialize<EvaluationResult>(jsonResponse);
            return result ?? new EvaluationResult { Score = 0, Reasoning = "Failed to parse evaluation result." };
        }
        catch (Exception ex)
        {
            return new EvaluationResult 
            { 
                Score = 0, 
                Reasoning = $"Error during evaluation: {ex.Message}" 
            };
        }
    }
}
